services:
  postgres:
    image: postgres:latest
    container_name: my-finance-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myfinance
      POSTGRES_USER: diti
      POSTGRES_PASSWORD: FinanceDbPassword
    networks:
      - financenet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-finance-pgadmin-container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
        - financenet

  zookeeper:
    image: wurstmeister/zookeeper:latest
    platform: linux/amd64
    ports:
      - "2181:2181"
    networks:
        - financenet

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "booking.topic:1:1,transaction.topic:1:1"
    depends_on:
      - zookeeper
    networks:
      - financenet

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.2.1
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_CONNECT_CLUSTER: kafka:9092
    networks:
      - financenet


  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
    depends_on:
      - kafka
    networks:
      - financenet


networks:
    financenet:
        driver: bridge