-- =============================================================================
-- V1 - Baseline schema (feature 021, release hardening)
-- =============================================================================
--
-- This file freezes the schema exactly as Hibernate's `ddl-auto=update` produced it up to and
-- including feature 020. It is a BASELINE, not a change: it adds nothing, tightens nothing, and
-- renames nothing. Features 001-020 are collapsed into this single starting point because no
-- released version ever had a different schema to migrate from.
--
-- It is applied on two different paths, and both must end at the same schema:
--
--   * A brand-new empty database EXECUTES this file (Flyway records type = SQL).
--   * An instance already running with real data does NOT execute it. `baseline-on-migrate=true`
--     stamps flyway_schema_history with a row of type = BASELINE at version 1, adopting the
--     existing tables untouched. This is what makes upgrading an operator's instance non-
--     destructive.
--
-- WHY THERE ARE ALMOST NO CONSTRAINTS HERE: cross-entity references (bill.account_id,
-- income.category_id, savings_goal.account_id, *.corrects_transaction_id) are plain varchar
-- columns because the JPA entities model them as String. Adding foreign keys here would be a
-- schema CHANGE disguised as a baseline, and it could fail against data an operator already has.
-- If those should become real foreign keys, that is a later migration with its own spec.
--
-- DO NOT EDIT THIS FILE. Flyway checksums applied migrations; editing it after any instance has
-- run it turns every subsequent startup into a validation failure. Schema changes go in V2, V3,
-- ... - never back into V1.
--
-- Regenerating this DDL (e.g. to derive the delta for a new migration) is documented in
-- specs/021-release-hardening/quickstart.md, "Developer scenario". Note that
-- org.hibernate.tool.hbm2ddl.SchemaExport does not exist in Hibernate 6.6.
-- =============================================================================

create table account (
    id uuid not null,
    balance numeric(38,2),
    default_currency varchar(255) not null,
    institution varchar(255),
    name varchar(255) not null unique,
    type varchar(255) not null,
    updated_at timestamp(6) with time zone,
    primary key (id)
);

create table account_currency (
    account_id uuid not null,
    currency_code varchar(255)
);

create table admin_account (
    id uuid not null,
    created_at timestamp(6) with time zone not null,
    password_hash varchar(255) not null,
    token_version integer not null,
    updated_at timestamp(6) with time zone,
    username varchar(255) not null,
    primary key (id)
);

create table allocation_transfer (
    id uuid not null,
    amount numeric(38,2) not null,
    created_at timestamp(6) with time zone not null,
    from_category_id varchar(255) not null,
    month integer not null,
    to_category_id varchar(255) not null,
    year integer not null,
    primary key (id)
);

create table bill (
    id uuid not null,
    account_id varchar(255),
    amount numeric(38,2),
    category_id varchar(255),
    corrects_transaction_id varchar(255),
    description varchar(255),
    necessity_tag varchar(255),
    necessity_tag_updated_at timestamp(6) with time zone,
    recorded_at timestamp(6) with time zone,
    reversal boolean default false not null,
    time timestamp(6) with time zone,
    primary key (id)
);

create table budget (
    id uuid not null,
    category_id varchar(255) not null,
    limit_amount numeric(38,2) not null,
    month integer not null,
    updated_at timestamp(6) with time zone,
    year integer not null,
    primary key (id),
    unique (category_id, year, month)
);

create table category (
    id uuid not null,
    color varchar(255),
    name varchar(255) not null unique,
    parent_category_id varchar(255),
    type varchar(255) not null,
    updated_at timestamp(6) with time zone,
    primary key (id)
);

create table income (
    id uuid not null,
    account_id varchar(255),
    amount numeric(38,2) not null,
    category_id varchar(255),
    corrects_transaction_id varchar(255),
    currency varchar(255),
    description varchar(255),
    notes varchar(255),
    payer varchar(255),
    recorded_at timestamp(6) with time zone,
    recurring boolean,
    recurring_frequency varchar(255),
    reversal boolean default false not null,
    source varchar(255),
    time timestamp(6) with time zone not null,
    primary key (id)
);

create table recurring_series (
    id uuid not null,
    created_at timestamp(6) with time zone not null,
    description varchar(255) not null,
    frequency varchar(255) not null,
    group_key varchar(255) not null,
    status varchar(255) not null,
    transaction_type varchar(255) not null,
    updated_at timestamp(6) with time zone,
    primary key (id)
);

create table savings_goal (
    id uuid not null,
    account_id varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    name varchar(255) not null,
    target_amount numeric(38,2) not null,
    target_date timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    primary key (id)
);

alter table if exists account_currency 
   add constraint FK1tgr7gw8nsslr01c5sn10cl16 
   foreign key (account_id) 
   references account;
