<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>at.ymeri</groupId>
        <artifactId>finance</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>Launcher</artifactId>

    <dependencies>
        <dependency>
            <groupId>at.ymeri</groupId>
            <artifactId>Application</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>at.ymeri</groupId>
            <artifactId>Domain</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>at.ymeri</groupId>
            <artifactId>Infrastructure</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
    </dependencies>


</project>