#!/usr/bin/env bash
# Creates .env with generated secrets, once. Runs from devcontainer.json's postCreateCommand.
#
# The point is that a fresh Codespace is one command away from running, without anyone pasting a
# password into a file — and without this repository ever shipping a default credential, which is
# the thing feature 021 existed to remove.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
    echo ".env already exists — leaving it untouched."
    exit 0
fi

secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 32 | tr -d '\n'
    else
        head -c 32 /dev/urandom | base64 | tr -d '\n'
    fi
}

cat > .env <<ENV
# Generated by .devcontainer/setup.sh for this Codespace. Not committed (.env is gitignored).
#
# These are throwaway values for a test instance. Regenerate them for anything you would mind
# someone else reaching: delete this file and re-run .devcontainer/setup.sh.
POSTGRES_PASSWORD=$(secret)
JWT_SECRET=$(secret)
PGADMIN_DEFAULT_PASSWORD=$(secret)
ENV

chmod 600 .env
echo "Wrote .env with generated secrets."
echo
echo "Start it with:"
echo "    docker compose -f docker-compose.deploy.yaml up -d --build"
