openapi: "3.0.0"
tags:
  - name: "IncomeGetController"
    description: "API for retrieving incomes from the system"
info:
  title: "Personal Finance Service - Find incomes API"
  description: "This API can be used to retrieve incomes from the system"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080/api/v1"
paths:
  /incomes:
    get:
      summary: "List all incomes"
      operationId: listIncomes
      description: "List all incomes of the current user"
      tags:
        - incomeGet
      parameters:
        - name: "date"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "date"
            example: '2023-10-26'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: 'income-model.yaml#/components/schemas/incomeResponseModel'
        "400":
          description: "Invalid"
        "404":
          description: "None found"
        default:
          description: "Unexpected error"
  /income/{id}:
    get:
      summary: "Get income by id"
      operationId: "getById"
      tags:
        - incomeGet
      parameters:
        - name: id
          in: path
          required: true
          description: "Income id"
          schema:
            type: string

      responses:
        "200":
          description: "A income object"
          content:
            application/json:
              schema:
                $ref: 'income-model.yaml#/components/schemas/incomeResponseModel'
        "400":
          description: "Invalid"
        "404":
          description: "Not found"
        default:
          description: "Unexpected error"

