openapi: "3.0.0"
info:
  title: "Personal Finance Service - Find Incomes API"
  description: "API to retrieve income entries from the system"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080/api/v1"
paths:
  /incomes:
    get:
      summary: "List all incomes"
      operationId: listIncomes
      description: "List all income entries"
      tags:
        - incomeGet
      parameters:
        - name: "date"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "date"
            example: "2023-10-26"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "income-model.yaml#/components/schemas/incomeListResponse"
        "400":
          description: "Invalid request"
        default:
          description: "Unexpected error"
  /incomes/{id}:
    get:
      summary: "Get income by id"
      operationId: getIncomeById
      tags:
        - incomeGet
      parameters:
        - name: id
          in: path
          required: true
          description: "Income id"
          schema:
            type: string
      responses:
        "200":
          description: "An income entry"
          content:
            application/json:
              schema:
                $ref: "income-model.yaml#/components/schemas/incomeResponse"
        "400":
          description: "Invalid request"
        "404":
          description: "Not found"
        default:
          description: "Unexpected error"
