#!/usr/bin/env bash
# Creates .env with generated secrets.
#
# Passbook ships no credentials — feature 021 removed the last of them, and every Compose service
# refuses to start without the ones it needs. That leaves a one-time setup step, and this is it.
#
# It exists because `cp .env.example .env` looks like it is enough and is not: the example has the
# keys with EMPTY values, and Docker Compose treats an empty required variable exactly like a
# missing one. The result is a .env that exists, looks filled in, and still fails every command
# with the same error — including `docker compose down`.
#
#   ./scripts/generate-env.sh            create .env if it is missing or incomplete
#   ./scripts/generate-env.sh --force    replace an existing .env (invalidates sessions, see below)
#
# Rotating JWT_SECRET logs out every existing session. Rotating POSTGRES_PASSWORD does NOT change
# the password on a database that already exists, so an existing instance will stop connecting —
# which is why --force is opt-in rather than the default.
set -euo pipefail

cd "$(dirname "$0")/.."

FORCE=false
if [ "${1:-}" = "--force" ]; then
    FORCE=true
fi

secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 "$1" | tr -d '\n'
    else
        head -c "$1" /dev/urandom | base64 | tr -d '\n'
    fi
}

# Reads a key's value from .env, tolerating absence. Only used to decide whether the file is
# actually usable, never printed.
value_of() {
    [ -f .env ] || return 0
    grep -E "^$1=" .env | tail -1 | cut -d= -f2- || true
}

if [ -f .env ] && [ "$FORCE" = false ]; then
    missing=""
    for key in POSTGRES_PASSWORD JWT_SECRET PGADMIN_DEFAULT_PASSWORD; do
        if [ -z "$(value_of "$key")" ]; then
            missing="$missing $key"
        fi
    done

    if [ -z "$missing" ]; then
        echo ".env already exists and every required value is set. Nothing to do."
        exit 0
    fi

    # The exact trap this script exists for. Say which keys are blank, rather than letting Compose
    # report one of them as "missing" in a file the operator can see is present.
    echo ".env exists but these values are empty:$missing" >&2
    echo >&2
    echo "That is what a plain 'cp .env.example .env' leaves behind — Compose treats an empty" >&2
    echo "value the same as an absent one. Fill them in by hand, or replace the file with" >&2
    echo "generated secrets:" >&2
    echo >&2
    echo "    ./scripts/generate-env.sh --force" >&2
    exit 1
fi

cat > .env <<ENV
# Generated by scripts/generate-env.sh. Gitignored, and never copied into a Docker image.
#
# Treat these as real credentials on any instance that holds data you care about.

# Password for the PostgreSQL role Passbook connects as.
POSTGRES_PASSWORD=$(secret 24)

# Signs session tokens. Changing it logs out every existing session, which is the correct
# response to a leak.
JWT_SECRET=$(secret 32)

# pgAdmin web UI (development only — pgAdmin is not part of a deployment).
PGADMIN_DEFAULT_PASSWORD=$(secret 16)
ENV

chmod 600 .env
echo "Wrote .env with generated secrets."
